### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rschramm9** [Appsilon/shiny.i18n#109]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### What happened?

When calling: Translator <- Translator$new(translation_csvs_path = "./data", separator_csv="|")
throws warning

"Warning in load_local_config(translation_csv_config) :
  You didn't specify config translation yaml file. Default settings are used."

I can find nothing in code or in your project examples regarding the yaml cfg.

Please describe a correct correct yaml config file.
Also please describe how to correctly 'specify'
Also related, there is nothing in the docs regarding the "default settings" are...

### Steps to reproduce

1.run your demo project.
2.observe in console: Warning in load_local_config(translation_csv_config) :
  You didn't specify config translation yaml file. Default settings are used.
...

### Expected behavior

No warnings

**Comment by jakubnowicki** [comment]
Hi @rschramm9,
Thank you for adding this issue. YAML file can be used to pass additional configurations like `cultural_date_format` when you use CSV (in JSON you can add it as one of the fields). You can find a little bit more [here](https://appsilon.github.io/shiny.i18n/articles/translation_format.html), but we will make sure that this feature is better documented.
