### ISSUE TITLE
Allow translating vectors

### ISSUE THREAD

**Issue by krystian8207** [Appsilon/shiny.i18n#28]
It would improve the usage a lot if we could pass vectors of keys to the translator.
An example:
```
i18n$t(c("key1", "key2"))
```
could return:
```
[1] "Key one" "Key two"
```

**Comment by SigurdJanson** [comment]
Is this still open?? I just did this `i18n$t(c("Result", "Ability"))` and it worked!

**Comment by dokato** [comment]
Thanks @SigurdJanson for suggestion. Indeed it should be easy this way, formatting warning shouldn't be a big issue. I'll try to include it soon.

**Comment by dokato** [comment]
@SigurdJanson it should be working now.
