### ISSUE TITLE
Error load_local_config function

### ISSUE THREAD

**Issue by AleVeraM** [Appsilon/shiny.i18n#29]
I'm trying to call the load_local_config function to load the configuration file, but it throws an error, it can't find it. What is the correct way to call this function?
`
library(shiny)
library(shiny.i18n)
load_local_config("../../config.yaml") # Throw error, not found
ui <- shinyUI(fluidPage(
    ......
))
translator <- Translator$new(translation_csvs_path = "../data")

server <- shinyServer(function(input, output, session) {
  ......
})
`

**Comment by krystian8207** [comment]
@AleVeraM 
Could you provide folders structure including `app.R` and `config.yml` file?
This way I could detect what should be the correct path.

**Comment by AleVeraM** [comment]
I am running the live_language_change example, I add the `load_local_config ("../../ config.yaml") `statement.
The error shown is that the function could not be found, RStudio autocomplete does not show that function.

**Comment by krystian8207** [comment]
@AleVeraM 
The problem is `load_local_config` is not an exported function in the package. In order to use it properly use:
```
translator <- Translator$new(
  translation_csvs_path = "../data",
  translation_csv_config = "../../config.yaml"
)
```

Please let me know if this fixed the problem.

**Comment by AleVeraM** [comment]
Fixed the problem.
Thanks!!
