### ISSUE TITLE
Semicolon-separated CSVs

### ISSUE THREAD

**Issue by oloverm** [Appsilon/shiny.i18n#35]
I just moved to a new country, where they use commas for decimals, so Excel saves CSVs with semicolons as separators. Giving them to the translator doesn't work.

Could there be an argument in to switch between `read.csv` and `read.csv2` (which uses semicolons) in `multmerge()`? I think that would solve the issue and make the package more internationally friendly. :)

**Comment by dokato** [comment]
Thanks, @oloverm for letting us know. Embarassingly, in my country, we also use commas for decimals, but I totally forgot about this edge-case. Thanks for the suggestion. This will be fixed soon!

**Comment by dokato** [comment]
This should be fixed in the latest version now. Soon on CRAN ;)

```r
18n <- Translator$new(translation_csvs_path = "csvs/", separator_csv = ";")
```
