### ISSUE TITLE
Cyrillic comes out as unicode

### ISSUE THREAD

**Issue by oloverm** [Appsilon/shiny.i18n#36]
This might be an issue with Shiny/R, rather than this package, sorry if so. I haven't dealt with encoding stuff before so this is all new to me.

I'm trying to translate from English to Russian. I've got the translator working fine when I tested it using the Latin alphabet. However, now that I've loaded in an actual Russian translation CSV, I've got trouble. These six unicode characters should say Привет (hello).

![cyrillic text shown as asshole unicode](https://user-images.githubusercontent.com/26772530/93877915-92d8b580-fcd9-11ea-9532-b9bbe3f401e8.png)

Is it this package that's showing the unicode, or do you guys know how to show it as Cyrillic?

**Comment by oloverm** [comment]
Ok, as I kind of suspected, it wasn't really an issue with shiny.i18n. It was a locale issue, I fixed it with `Sys.setlocale("LC_ALL", "Russian_Russia")`. I found the Windows locale to use on [this website](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c). Apparently it's a bit simpler on Mac/Unix.

**Comment by dokato** [comment]
Thank you @oloverm for reporting that, indeed we should mention in the readme to be careful with local language settings while reading the data.
