### ISSUE TITLE
Translation for radioButton() choices and selectInput()

### ISSUE THREAD

**Issue by mcsiple** [Appsilon/shiny.i18n#54]
Hi shiny.i18n team,

I know I have seen questions about this before but I can't find a solution -- I need to find a way to translate the `choices` in my selectInput() and `radioButtons()` inputs. If I try to wrap choice labels with `i18n$t()`, the app does not run. I don't know if this is a feature in the package yet, but if it isn't, would you mind offering some best practices for how people should get by in the meantime? 

I am doing live translation and using `uiOutput(page_content)` in my UI to do automatic translation when the user selects a radio button with the language on it. I don't need to update the language selection radio buttons themselves, but I need it for other `radioButton` inputs and a dropdown `SelectInput()` with common names of species. 

Thank you in advance for your help.

**Comment by mehdihadi** [comment]
This was just my issue, I resolved this using following function. It works for me. Hope you find it useful too.

trF<-function(x){
    a<- i18n$t(x) 
  a<-gsub( "\""  , "'", a, fixed = TRUE)
  a<-noquote(a)
  a<-gsub("'", '"', a, fixed = T)
  a<-unlist(strsplit(a, split=","))
  gsub("\"", "", a, fixed = T)
}

use single quotation mark (') around x argument.

**Comment by dokato** [comment]
hey @mcsiple , because both radio button as select input are dynamic elements, they need to be updated with respective update functions from `shiny` on the server-side (for instance `updateSelectInput`). Thus, in this example, I'd suggest using server-side translation. For example:

```r
library(shiny)
library(shiny.i18n)

i18n <- Translator$new(translation_json_path = "translation.json")

ui <- fluidPage(
  usei18n(i18n),
  h1(i18n$t("Hello")),
  actionButton("change", i18n$t("Change language")),
  radioButtons("radio", i18n$t("Radio"), c("one", "two")),
  p("---"),
  selectInput("select", i18n$t("Choose"), c("one", "two", "three"))
)

server <- function(input, output, session) {

  i18n_r <- reactive({
    i18n
  })

  observeEvent(input$change, {
    lang <- ifelse(as.numeric(input$change) %% 2, "pl", "en")
    shiny.i18n::update_lang(session, lang)
    i18n_r()$set_translation_language(lang)
  })

  observe({
    updateRadioButtons(session, "radio", label = i18n_r()$t("Radio"),
                       choices = i18n_r()$t(c("one", "two")))
    updateSelectInput(session, "select", label = i18n_r()$t("Choose"),
                      choices = i18n_r()$t(c("one", "two", "three")))
  })
}
shinyApp(ui, server)
```

Note that I create a reactive variable `i18n_r()` from our translation object. LMK if this example is not clear.

**Comment by mcsiple** [comment]
Success! It worked. Thank you @dokato , this is great.

**Comment by mickeykawai** [comment]
@ainhoavega : 

I solved as follows. 

`library(shiny)
library(shiny.i18n)

i18n <- Translator$new(translation_json_path = "translation.json")

choices_select <- c("one", "two", "three")

ui <- fluidPage(
  usei18n(i18n),
  h1(i18n$t("Hello")),
  actionButton("change", i18n$t("Change language")),
  radioButtons("radio", i18n$t("Radio"), c("one", "two")),
  selectInput("select", i18n$t("Choose"), c("one", "two", "three")),
  verbatimTextOutput("select")
)

server <- function(input, output, session) {
  
  i18n_r <- reactive({
    i18n
  })
  
  observeEvent(input$change, {
    lang <- ifelse(as.numeric(input$change) %% 2, "pl", "en")
    shiny.i18n::update_lang(session, lang)
    i18n_r()$set_translation_language(lang)
  })
  
  
  update_choices_select <- reactive({
    names(choices_select) <- i18n_r()$t(choices_select)
    print(choices_select)
    choices_select
  })
  
  observe({
    updateRadioButtons(session, "radio", label = i18n_r()$t("Radio"),
                       choices = i18n_r()$t(c("one", "two")))
    updateSelectInput(session, "select", label = i18n_r()$t("Choose"),
                      choices = update_choices_select())
                      #choices = i18n_r()$t(update_choices_select()))
                      #choices = i18n_r()$t(c("one", "two", "three")))
  })
  
  output$select <- renderText({ 
    input$select
  })
}
shinyApp(ui, server)
`

**Comment by ReedMerrill** [comment]
> hey [@mcsiple](https://github.com/mcsiple) , because both radio button as select input are dynamic elements, they need to be updated with respective update functions from `shiny` on the server-side (for instance `updateSelectInput`). Thus, in this example, I'd suggest using server-side translation. For example:
> 
> library(shiny)
> library(shiny.i18n)
> 
> i18n <- Translator$new(translation_json_path = "translation.json")
> 
> ui <- fluidPage(
>   usei18n(i18n),
>   h1(i18n$t("Hello")),
>   actionButton("change", i18n$t("Change language")),
>   radioButtons("radio", i18n$t("Radio"), c("one", "two")),
>   selectInput("select", i18n$t("Choose"), c("one", "two", "three"))
> )
> 
> server <- function(input, output, session) {
> 
>   i18n_r <- reactive({
>     i18n
>   })
> 
>   observeEvent(input$change, {
>     lang <- ifelse(as.numeric(input$change) %% 2, "pl", "en")
>     shiny.i18n::update_lang(session, lang)
>     i18n_r()$set_translation_language(lang)
>   })
> 
>   observe({
>     updateRadioButtons(session, "radio", label = i18n_r()$t("Radio"),
>                        choices = i18n_r()$t(c("one", "two")))
>     updateSelectInput(session, "select", label = i18n_r()$t("Choose"),
>                       choices = i18n_r()$t(c("one", "two", "three")))
>   })
> }
> shinyApp(ui, server)
> 
> Note that I create a reactive variable `i18n_r()` from our translation object. LMK if this example is not clear.

Thanks for the example. One quick question: is that only possible to translates entire vectors in one shot if the translation file is JSON?

**Comment by ReedMerrill** [comment]
> hey [@mcsiple](https://github.com/mcsiple) , because both radio button as select input are dynamic elements, they need to be updated with respective update functions from `shiny` on the server-side (for instance `updateSelectInput`). Thus, in this example, I'd suggest using server-side translation. For example:
> 
> library(shiny)
> library(shiny.i18n)
> 
> i18n <- Translator$new(translation_json_path = "translation.json")
> 
> ui <- fluidPage(
>   usei18n(i18n),
>   h1(i18n$t("Hello")),
>   actionButton("change", i18n$t("Change language")),
>   radioButtons("radio", i18n$t("Radio"), c("one", "two")),
>   selectInput("select", i18n$t("Choose"), c("one", "two", "three"))
> )
> 
> server <- function(input, output, session) {
> 
>   i18n_r <- reactive({
>     i18n
>   })
> 
>   observeEvent(input$change, {
>     lang <- ifelse(as.numeric(input$change) %% 2, "pl", "en")
>     shiny.i18n::update_lang(session, lang)
>     i18n_r()$set_translation_language(lang)
>   })
> 
>   observe({
>     updateRadioButtons(session, "radio", label = i18n_r()$t("Radio"),
>                        choices = i18n_r()$t(c("one", "two")))
>     updateSelectInput(session, "select", label = i18n_r()$t("Choose"),
>                       choices = i18n_r()$t(c("one", "two", "three")))
>   })
> }
> shinyApp(ui, server)
> 
> Note that I create a reactive variable `i18n_r()` from our translation object. LMK if this example is not clear.

This code now gives an `Error in $: $ operator is invalid for atomic vectors` error. The fix is to use `reactiveValues` instead of `reactive` when creating `i18n_r`, which allows modifying `i18n_r$translator` dynamically. You then need to wrap the text to translate with `i18n_r$translator$t()` instead of `i18n_r()$t()`. Here's the full example:

```r
library(shiny)
library(shiny.i18n)

i18n <- Translator$new(translation_json_path = "translation.json")

ui <- fluidPage(
  usei18n(i18n),
  h1(textOutput("title")),
  actionButton("change", "Change language"),
  radioButtons("radio", "Radio", choices = c("one", "two")),
  selectInput("select", "Choose", choices = c("one", "two", "three"))
)

server <- function(input, output, session) {
  # Store the translator inside a reactiveValues object
  i18n_r <- reactiveValues(translator = i18n)

  observeEvent(input$change, {
    lang <- ifelse(as.numeric(input$change) %% 2, "fr", "en")

    # Update the translator language
    i18n_r$translator$set_translation_language(lang)

    # Update UI elements dynamically
    updateRadioButtons(session, "radio",
      label = i18n_r$translator$t("Radio"),
      choices = i18n_r$translator$t(c("one", "two"))
    )
    updateSelectInput(session, "select",
      label = i18n_r$translator$t("Choose"),
      choices = i18n_r$translator$t(c("one", "two", "three"))
    )
    updateActionButton(session, "change",
      label = i18n_r$translator$t("Change language")
    )
  })

  output$title <- renderText({
    i18n_r$translator$t("Hello")
  })
}

shinyApp(ui, server)
```
