### ISSUE TITLE
UTF encoding and special characters during golem deployment

### ISSUE THREAD

**Issue by mcsiple** [Appsilon/shiny.i18n#66]
Hi Appsilon developers! 
I built an app using `golem` because I hope to publish it as an R package. 

I am using live translation in the app via radioButtons. The .json file with my translations contains special characters. When I deploy the app from the [R package](https://github.com/mcsiple/mmrefpoints) to shinyapps.io , the [version that publishes](https://msiple.shinyapps.io/mmrefpoints/) to the server does not display these special characters at all (notice how the í is missing from "vaya aquí"):
![Screen Shot 2021-08-25 at 6 18 15 PM](https://user-images.githubusercontent.com/2936426/130884505-71660ce0-d01a-4b3f-895c-d450f2e697ca.png)

Special characters included in the [app_ui.R](https://github.com/mcsiple/mmrefpoints/blob/master/R/app_ui.R) file render as UTF on the server:
![Screen Shot 2021-08-25 at 6 17 26 PM](https://user-images.githubusercontent.com/2936426/130884449-50df1939-72fd-44dc-a54b-dd94794f32a9.png)

I am not sure if this is a `golem` issue or a `shiny.i18n` issue, but I am posting here because I am guessing other `shiny.i18n` users have similar issues. I have to keep both types (the .json contents and the in-app special characters) in order to allow translation for the radioButton options and the plots. 

Here is the repo for the R package (everything works perfectly when the app is deployed from the package): https://github.com/mcsiple/mmrefpoints
Here is the server version that deploys automatically when I use `golem::add_shinyappsio_file(); rsconnect::deployApp()`:
https://msiple.shinyapps.io/mmrefpoints/

If I should post this on the `golem` github page instead, just let me know. And thank you in advance for your help.

**Comment by owen-cho** [comment]
Thanks @mcsiple , it was indeed helpful.
So you used `switch` function inside your server instead of `shiny.i18n` translator. I managed to get it working this way, but wonder if you've done the same. Thanks!

**Comment by mcsiple** [comment]
Hi @owen-cho indeed, this is what I used. Here's an example code chunk for what those HTML pieces look like in my code:

In the constants file that loads before the app runs:
```
splash_es <- "<div class='jumbotron'>
  <h2>Bienvenido a la herramienta de exploraci&oacute;n de impactos de la captura incidental de mam&iacute;feros marinos</h2>
</div>"
```
In the server code:
```
 output$splash <- renderUI({
    htmltools::HTML(
      switch(input$selected_language,
        "en" = splash_en,
        "es" = splash_es,
        "fr" = splash_fr
      )
    )
  })
```

I hope this helps!

**Comment by owen-cho** [comment]
Thank you @mcsiple 
I did pretty much the same:
```
library(shiny)
library(tidyverse)

ui <- fluidPage(
  actionButton("btn", "Welcome"),
  selectInput("lang", NULL, c("en", "kr"))
)

server <- function(input, output, session) {
  observeEvent(input$lang, {
    label <- switch(
      input$lang,
      en = "Welcome",
      kr = HTML("&#xd658;&#xc601;&#xd569;&#xb2c8;&#xb2e4;")
    )
    updateActionButton(inputId = "btn", label = label)
  })
}

shinyApp(ui = ui, server = server)
```
